<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOOKLIST [
  <!ELEMENT BOOKLIST (BOOK)*>
  <!ELEMENT BOOK (AUTHOR)>
  <!ELEMENT AUTHOR (FIRSTNAME, LASTNAME)>
  <!ELEMENT FIRSTNAME (#PCDATA)>
  <!ELEMENT LASTNAME (#PCDATA)>
  <!ATTLIST BOOK GENRE (Science | Fiction) #REQUIRED>
  <!ATTLIST BOOK FORMAT (Paperback | Hardcover) "Paperback">
]>
<BOOKLIST>
  <BOOK GENRE="Science" FORMAT="Hardcover">
    <AUTHOR>
      <FIRSTNAME>RICHRD</FIRSTNAME>
      <LASTNAME>KARTER</LASTNAME>
    </AUTHOR>
  </BOOK>
</BOOKLIST>
